version: "3"
services:
  react-app:
    container_name: react-app
    restart: always
    build: ./client/
    ports: 
      - "3000:3000"
  api-server:
    container_name: api-server
    restart: always
    build: ./server/
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo-database
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none